### ISSUE TITLE
Configuration option 'direction' does not work anymore (with db profile)

### ISSUE THREAD

**Issue by evroom** [KristjanESPERANTO/MMM-PublicTransportHafas#193]
MMM-PublicTransportHafas
release v3.0.1

(git pull && npm ci where used to get the latest code)

The configuration option 'direction' does not work (anymore).
When setting the parameter with the station ID of the station adjacent to the stationID, it still shows the other directions too.

Configuration used:
```js
  {
    module: "MMM-PublicTransportHafas",
    disabled: false,
    position: "top_right",
    header: "DEPARTURES",
    config: {
      hafasProfile: "db",
      stationID: "8004491",
      stationName: "Nürnberg-Rehhof",
      updatesEvery: 60,
      timeInFuture: 180,
      direction: "",
      //direction: "8005185", // Roth
      direction: "682675", // Mögeldorf Bahnhof, Nürnberg
      ignoredLines: [],
      excludedTransportationTypes: ["bus"],
      timeToStation: 5,
      displayLastUpdate: true,
      displayLastUpdateFormat: "dddd MMM D - HH:mm",
      showColoredLineSymbols: true,
      useColorForRealtimeInfo: true,
      noRealtimeDelayString: "⚠",
      showTableHeadersAsSymbols: true,
      maxUnreachableDepartures: 2,
      maxReachableDepartures: 10,
      customLineStyles: "nuernberg",
      showOnlyLineNumbers: true
    }
  },
```

It can be that this is the result of the necessary change from the 'db' profile to the db-vendo-client'.

**Comment by ggruening** [comment]
+1

**Comment by KristjanESPERANTO** [comment]
Should be fixed now with release 3.0.2 :slightly_smiling_face: 

Please confirm.

**Comment by ggruening** [comment]
Recently, I tested the workaround provided by @KristjanESPERANTO , but unfortunately, it did not perform as expected. While it successfully filters the departures to show only those trains that have the specified destination as their **final stop**, it incorrectly excludes trains that pass through the destination at any point in their route.

I kindly request that this filtering functionality be further improved to ensure that all relevant departures are displayed accurately. It would greatly enhance the usability of the system for passengers who are looking to travel to specific destinations.

Thank you for your attention to this matter. I appreciate your efforts in making our public transport experience better!

Gregor

**Comment by KristjanESPERANTO** [comment]
@ggruening At the moment I can hardly imagine how the workaround creates this effect. The workaround filters based on information about the direction, stops on the route are not treated at all. Didn't this behaviour already occur with 3.0.1 or 3.0.0?
In any case, I need more info (like the config and which directions are being falsely filtered) to investigate.

@evroom How is the new version working for you?

**Comment by ggruening** [comment]
@KristjanESPERANTO I'm not quite sure which version I last used. I can find that out later today or tomorrow, as I'm currently not at home. In the older versions, the effect of 'direction' has been as I described for years. It seems reasonable to me: as a commuter, all trains that reach a specific destination are helpful. The route is actually irrelevant; what matters is that the destination appears at some point during the journey. Perhaps the 'direction' parameter has always been intended differently, but that is indeed what helps me, at least. I will gladly provide my configuration later today or tomorrow, but maybe my use case will already help: 'show all departures from Münster(Westf)Hbf to Dortmund(Hbf)' (all in Germany from Deutsche Bahn). Thank you for considering this! Best regards!

**Comment by blinkybob** [comment]
I had the same problem as @evroom with the direction I updated the module to 3.0.2
Now I have zero departures listed on the screen. Before the update there were three to four ones. 

Here is my config:

```js client
{
module: "MMM-PublicTransportHafas",
        position: "bottom_left",
        config: {
                // Departures options
                stationID: "8005976",             // Replace with your stationID!
                stationName: "Unterasbach",       // Replace with your station name!
                direction: "8004486",             // Show only departures heading to this station. (A station ID.)
                excludedTransportationTypes: [],  // Which transportation types should not be shown on the mirror? (comma-separated list of types) possible values: "tram", "bus">
                ignoredLines: [],                 // Which lines should be ignored? (comma-separated list of line names)
                timeToStation: 9,                // How long do you need to walk to the next Station?
                timeInFuture: 90,

                // Look and Feel
                displayLastUpdate: true,          // Display the last time of module update.
                maxUnreachableDepartures: 2,      // How many unreachable departures should be shown?
                maxReachableDepartures: 7,        // How many reachable departures should be shown?
                showColoredLineSymbols: true,     // Want colored line symbols?
                customLineStyles: "",             // Prefix for the name of the custom css file. ex: Leipzig-lines.css (case sensitive)
                showOnlyLineNumbers: false,       // Display only the line number instead of the complete name, i. e. "11" instead of "STR 11"
                showTableHeadersAsSymbols: true,  // Table Headers as symbols or text?
                useColorForRealtimeInfo: true     // Want colored real time information (timeToStation, early)?
                }
        }
```

**Comment by evroom** [comment]
It works, but it is kind of useless for me.
But ...  it greatly depends on the ```direction``` station ID that is being used.

Part of my config:
```
      hafasProfile: "db",
      stationID: "8004491", // Nürnberg-Rehhof
      direction: "", // [ Schwabach - Roth - Lauf(links Pegnitz) - Hersbrück(l Pegnit) - Hartmannshof ]
      //direction: "682675",  // Mögeldorf Bahnhof, Nürnberg (not okay)
      //direction: "8004481", // Nürnberg-Mögeldorf (not okay)
      //direction: "8005185", // Roth (okay)
      //direction: "8005439", // Schwabach (okay)
      //direction: "683437",  // Bahnhof, Schwabach (not okay)
      //direction: "8000284", // Nürnberg Hbf (not okay)
      //direction: "682669",  // Hauptbahnhof, Nürnberg (not okay)
      //direction: "8004480", // Nürnberg-Laufamholz (not okay)
      //direction: "8005451", // Schwaig (not okay)
      //direction: "683039",  // Hartmannshof Bahnhof, Pommelsbrunn (not okay)
      //direction: "8003580", // Lauf(links Pegnitz) (okay)
      //direction: "8002793", // Hersbrück(l Pegnitz) (okay)
      //direction: "8002612", // Hartmannshof (okay)
      //direction: "683039",  // Hartmannshof Bahnhof, Pommelsbrunn (not okay)
      ignoreRelatedStations: true,
```
 So, it only works for directions that are on the list when run with ```direction: ""```.
This needs to be a one-on-one match.
The ```ignoreRelatedStations: true``` does not seem to make any difference, btw.

For me it is not useful as I mainly travel with the S2 to Nürnberg Hbf and sometimes to Schwaig.
Showing 2 separate boards for the 2 directions does not make great sense and it would not work for the direction Schwaig.

**Comment by ggruening** [comment]
Perhaps departures in a specific `direction` are not what I and others are really looking for. It might be worth considering a display of the next connections from one station to a specific `destination`. That would certainly be a perfect feature for commuters ;-)

**Comment by lklinge** [comment]
Without direction the module shows me all trains departing from the starting station. S-Bahn (S) and Regional Express (RE) trains.

As soon as I enter a destination station in “direction” only the S-Bahn trains are displayed. And the Regional Express is missing.

**Comment by KristjanESPERANTO** [comment]
I probably won't have time to look at the problem until next week.

**Comment by KristjanESPERANTO** [comment]
Okay, I've had a look.

Let me elaborate a little: The `hafas-client` direction option really worked so that you could enter a stop on the route. Since Deutsche Bahn has apparently shut down the server that the `hafas-client` used for the `db` profile, we no longer received any departures for this module.

To make the `db` profile work again, we switched to the [db-vendo-client](https://github.com/public-transport/db-vendo-client) with version 3. This new client has almost the same functionalities as the `hafas-client`. So we've got our departures back 🙂 

Unfortunately, the `db-vendo-client` is only almost complete - the `direction` option is not yet functional, which is stated in the [README of the client](https://github.com/public-transport/db-vendo-client?tab=readme-ov-file#db-vendo-client).

So I see the following options for you:

1. participate in the development of `db-vendo-client` and fix the problem yourself. My focus is currently on other projects.
2. check whether a profile other than the `db` profile might work for your stop (checkout the README for that). The `hafas-client` is still used for other profiles, which is why the `direction` option works there. Remember that you will most likely have to use different IDs for other profiles.
3. if you only have one line coming along, you can enter the ID of the end point for the direction. This works with the above-mentioned workaround that I have included here in the module.
4. switch off the direction option and wait until someone fixes the problem in `db-vendo-client`.

Even if it is an upstream issue, I leave the issue open so that others can see that the problem is known, but needs to be fixed elsewhere.

**Comment by evroom** [comment]
Thanks for looking into it and the extensive comment.
I personally do not use it, but good that is has been investigated.

Thx!

**Comment by traines-source** [comment]
For clarification: It's not that I chose to not implement it in `db-vendo-client` so far, it's because the DB APIs don't offer this parameter anymore (or we don't know it). (And as you have discovered, we can't just filter by the direction/destination field because that excludes trips that pass by that station.)
There is the bahn.de boards API that is not implemented yet that at least returns some stopovers/`ueber` by which you could filter (but still not all, so it's not very helpful), and there is the [RIS::Boards API](https://developers.deutschebahn.com/db-api-marketplace/apis/product/ris-boards-transporteure) that apparently returns all stopovers, although I'm not sure how reliable that is. And crucially, this API is paid if you don't find an API key somewhere 👀 ^^
(Also see https://github.com/public-transport/db-vendo-client/issues/3)
When only trains are of interest (i.e. no buses etc.) the DB IRIS API might also be worth a try (but I currently don't see that to be implemented as part of `db-vendo-client`, especially because I have a feeling that it could also be shut down at some point, but I don't know).

**Comment by ggruening** [comment]
@KristjanESPERANTO
I'm not really sure, but the `db-vendo-client` can provide `connections`. Maybe it helps to take a closer look:
 [https://github.com/public-transport/db-vendo-client/blob/main/docs%2journeys.M](see here.) 

Instead of a `direction` from a station, we would then have a start station and a destination station as a 'direction'. May this work?

**Comment by traines-source** [comment]
That's actually not a bad idea, if you additionally set `transfers=0` to get only direct connections, the result should be exactly the same as a filtered departure board, if I'm not missing anything. (But you will only get 3-4 results and there doesn't seem to be an option to get more within a single request with the new DB APIs.)

**Comment by KristjanESPERANTO** [comment]
@traines-source: Thanks for the clarification and huge thanks for `db-vendo-client`, it really saves us here 😃

@ggruening: Yes, I also think that the idea is good and that it could work. Do you feel like trying to implement this and creating a PR?

**Comment by ggruening** [comment]
@KristjanESPERANTO @traines-source 
Thank you for considering my suggestion. Unfortunately, I lack the skills required for JavaScript development. While I can read some code and would be happy to help with testing, I'm not able to contribute to the actual development process. I hope that someone with the right skills will pick up this suggestion and implement it. I look forward to seeing how this feature evolves.

**Comment by traines-source** [comment]
Well we all had to learn it (by doing) at some point :)

Btw, this would also show cancelled trips, which I think is helpful (if you're exposing the remarks/cancelled flag, haven't checked), while with the `db` profile you seem to be using, cancelled trips are not returned! (And in the `dbnav` profile they are returned but boards are limited to one hour...)

**Comment by traines-source** [comment]
With the new version `6.5.0` of `db-vendo-client`, I've now experimentally implemented an artificial `direction` filter for the boards. Caveats:
* it only works with the `dbweb` profile, which may have other drawbacks (see [readme](https://github.com/public-transport/db-vendo-client/tree/main))
* filtering by IBNR/evaNr only works in conjunction with `enrichStations`, which is enabled by default, but is unreliable for new/modified stations
* filtering by exact (!) name should always work (but is actually an undocumented/new behavior)
* I am not sure how reliable the returned via/stopover stations are, based on which the filtering is done, but so far they seemed complete to me.

**Comment by lzptr** [comment]
I installed the `6.5.0` `db-vendo-client` and I can confirm that using "dbweb" as a `hafasProfile` does return the filtered connections by direction. Thanks @traines-source!
But I had to hack the "dbweb" option into the core/DepartureFetcher.js.
If anyones interrested, my quick fix was adding the "dbweb" check to the if clause:
```
 async init () {
    let createClient;
    let profile;
    if (this.config.hafasProfile === "db" || this.config.hafasProfile === "dbweb") {
      Log.info("[MMM-PublicTransportHafas] Using vendo client");
```

**Comment by KristjanESPERANTO** [comment]
Thanks @traines-source and @lklinge! I've just released a new version (3.1.2) which should fix the issue.

Users who want to use the direction option with the `db` profile need to switch to the `dbweb` profile.

**Comment by lklinge** [comment]
@KristjanESPERANTO Many thanks for your efforts. But I still have one question.

I am now trying to find the StationID via the dbweb profile.

I proceed as described above. But I still get the message that the db profile is used for the query.

`pi@raspi-mm-bad:~/MagicMirror/modules/MMM-PublicTransportHafas $ npm run query

> mmm-publictransporthafas@3.1.2 query
> node ./convenience/query_stations.mjs

Using db-vendo profile: db
`

What is going wrong?

**Comment by KristjanESPERANTO** [comment]
@lklinge On the first try I couldn't get the IDs from `dbweb`, but `db` returns the correct IDs for `dbweb`. Can you try that?

I should somehow adjust the output to express this. I reopen the issue as a reminder for me.

**Comment by KristjanESPERANTO** [comment]
If I understand correctly, you can only query one hour in the future with `dbweb`.

**Comment by KristjanESPERANTO** [comment]
Okay, I have now added a note if someone want to query station IDs with the `dbweb` profile and have added a note about the one hour limitation to the README.

**Comment by lklinge** [comment]
Great! Thanks! 
It seems there is an issue about the forecast. Yes, I mean the query is one hour in the future. And to be honest, I am not sure about that. I take a look at 7:28 am and the train at 08:25 am will not be displayed. 

But I am glad, that it works now with direction.
