### ISSUE TITLE
Conflict maxUnreachableDepartures

### ISSUE THREAD

**Issue by mazim-co** [KristjanESPERANTO/MMM-PublicTransportHafas#29]
**Bug description**
As soon as I add a number of `maxUnreachableDepartures` (e.g. 3) it is not showing `maxReachableDepartures` anymore.

**Module config**
```
{    
module: "MMM-PublicTransportHafas",
		position: "top_right",
			config: {
				stationID: "732872",                  
				stationName: "Albertinenstraße",   
				direction: "",                    
				excludedTransportationTypes: [], 
				ignoredLines: [],                
				timeToStation: 7,
				showAbsoluteTime: false,
				displayLastUpdate: false,         
				maxUnreachableDepartures: 3,     
				maxReachableDepartures: 5,        
				showColoredLineSymbols: true,    
				customLineStyles: "berlin",             
				showOnlyLineNumbers: true,   
				showTableHeadersAsSymbols: true, 
				useColorForRealtimeInfo: true,  
				tableHeaderOrder: [ "line", "direction", "time" ]
				}
},
```
**Screenshots**
```
maxUnreachableDepartures: 3,     
maxReachableDepartures: 5,
```
![image](https://user-images.githubusercontent.com/60115873/149174277-c5745c6e-41fe-420f-ac12-67e04192131e.png)

```
maxUnreachableDepartures: 0,     
maxReachableDepartures: 5,
```
![image](https://user-images.githubusercontent.com/60115873/149174427-1b245b33-356e-4f5b-92fc-7179915e973b.png)

**Additional context**
It is working properly if I'm not using the option `maxUnreachableDepartures`

**Comment by KristjanESPERANTO** [comment]
Thanks for the good description of the issue.

With [my last commit](https://github.com/KristjanESPERANTO/MMM-PublicTransportHafas/commit/fe599d434b76280162870ff3251377950e11a4f6) it should be solved. Please update the module and check whether it works now.

By the way: Have you created an extra css file for berlin? The line `customLineStyles:" berlin "` indicates this. I would be interested in what you defined there.

**Comment by mazim-co** [comment]
Thanks for the quick response. Unfortunately the changes doesn't fixed the issue. It is still the same weird behavior. It feels it has a conflict with the `timeToTravel` option. You can may test it with my `stationID: 732872`.

Yes, I created a full stylesheet for berlin lines which include all public transportation. I'm happy to share that with you. :) Just let me know how to upload the file.

**Comment by mazim-co** [comment]
Oh, never mind. I missed to perform a `npm install` after `git pull` 😅. Everything is working as expected. Thank you.

**Comment by KristjanESPERANTO** [comment]
Nice that it works 🙂

**Comment by mazim-co** [comment]
Hi Kristjan - just noticed that the issue appears again. It was working for 4-5 hours.

![image](https://user-images.githubusercontent.com/60115873/149367153-2ef93514-703e-414a-9786-58aabb555ded.png)

**Comment by KristjanESPERANTO** [comment]
I'll see if I can take a closer look at it over the weekend.

Of course, I am also grateful for participation :slightly_smiling_face:

**Comment by KristjanESPERANTO** [comment]
The problem was that there are very very many departures at Alexanderplatz. And therefore too many departures during the lead time.

I solved it by setting the lead time lower by default and adding a dynamic adjustment. So at stations with a lot of departures the lead time will be reduced and at stations with few departures the lead time will be increased.

**Comment by mazim-co** [comment]
Just want to say thank you! It works like charm - you rock 💪

**Comment by KristjanESPERANTO** [comment]
Thanks for the motivating feedback 😀
